import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header style={{ borderBottom: '1px solid #e6e6e6', padding: '12px 20px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div style={{ display: 'flex', gap: 16, alignItems: 'center' }}>
            <a href="/" style={{ textDecoration: 'none', color: 'inherit', fontWeight: 600 }}>Home</a>
            <a href="/analytics" style={{ textDecoration: 'none', color: 'inherit' }}>Analytics</a>
          </div>
          <div style={{ fontSize: 13, color: '#666' }}>Technicians Business</div>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
